### ISSUE TITLE
It doesn't really work at all

### ISSUE THREAD

**Issue by lluisandreu** [Naxon/nova-field-sortable#11]
Hi folks, 

I implemented this package as said in the instructions but can't make it work, when I click on the arrows I get a page refresh and nothing changes. Here's my code:

```
use Naxon\NovaFieldSortable\Concerns\SortsIndexEntries;
use Naxon\NovaFieldSortable\Sortable;

class Area extends Resource
{
    use SortsIndexEntries;
    public static $defaultSortField = 'order';

public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Number::make('Orden', 'order')->sortable()->min(0)->step(1),

            Sortable::make('Orden', 'id'),

        ];
}
...
```

And in the model Class

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\EloquentSortable\Sortable;
use Spatie\EloquentSortable\SortableTrait;

/**
 * App\Area
 *
 * @property-read \App\MetaField $meta
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Post[] $posts
 * @mixin \Eloquent
 */
class Area extends Model implements Sortable
{
    use SortableTrait;

    public $sortable = [
        'order_column_name' => 'order',
        'sort_when_creating' => true,
    ];

    public function meta() {
    	return $this->morphOne('App\MetaField', 'entity');
    }

    public function posts() {
    	return $this->belongsToMany('App\Post', 'post_area_pivot');
    }
}
```

**Comment by voidgraphics** [comment]
Kinda similar problem. 

In my case, the bottom arrow does bring the item down, but the up arrow does not work. I do get page refreshes, but it doesn't move up.

**Comment by voidgraphics** [comment]
Nevermind. I didn't read the documentation properly, and didn't see that at step 4 when you add the `Sortable` field, the second parameter needs to be the primary key, and NOT the sortable column name.

It works fine for me now.

**Comment by adick** [comment]
Doesn't seem to work on Nova 1.2, as @lluisandreu said, the page refreshes after clicking a sort arrow, but nothing happens with the sorting column.

**Comment by dillingham** [comment]
Im using it on 1.2.1 and it works

**Comment by Naxon** [comment]
Working on v2 that will support only newer versions.
