### ISSUE TITLE
Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by libastian** [Naxon/nova-field-sortable#12]
In the creation of any entity with ordination, this console error is thrown:

app.js?id=f1809770ce8acfb0a3ac:1 Uncaught (in promise) TypeError: Cannot read property 'status' of undefined

I have checked that everything works correctly when deactivating the sorting.

**Comment by pravk** [comment]
One workaround till this gets fixed is to load the field only on index page.

Sortable::make(...)**->onlyOnIndex()**

**Comment by Abhi0725** [comment]
Any news on this? or the above is the only only solution?

**Comment by Naxon** [comment]
Fixed in v2 in https://github.com/Naxon/nova-field-sortable/commit/748f5c32ba9081308660f18edde48f6bbd9ffc1c .

@pravk 's solution will also work, added to this version's readme.
