### ISSUE TITLE
Question - How translate the package ? 

### ISSUE THREAD

**Issue by InfinityWebMe** [Naxon/nova-field-sortable#18]
Hello,

How i translate the package ? I create a file fr.json in directory /resources/lang/vendor/nova-field-sortable with this content : 
`
{
    "The new order has been set!": "Ressource triée"
}
`
But it's doesn't work :/

Any idea ? 

Thanks :)

**Comment by InfinityWebMe** [comment]
Any idea ? :/

**Comment by gmarineau** [comment]
Any news about this issue ? Thanks for the package !

**Comment by InfinityWebMe** [comment]
Use "/resources/lang/vendor/nova/" :)
