### ISSUE TITLE
Package abandoned?

### ISSUE THREAD

**Issue by royduin** [Naxon/nova-field-sortable#21]
@dillingham says here: https://github.com/dillingham/nova-field-sortable this repo is abandoned but @jBOKA here: https://github.com/Naxon/nova-field-sortable/pull/17#issuecomment-453940063 doesn't admit this. Is this package abandoned or not @Naxon? Should we use @dillingham his package from now on? If so; maybe update the readme of this repo to link everybody to that repo and update it on novapackages.com?

**Comment by BobbyBorisov** [comment]
@royduin it looks like @dillingham packages is also abandoned? what are you using now?

**Comment by royduin** [comment]
Still using @dillingham his package but haven't worked much on that project lately so didn't notice it was removed. Maybe @dillingham can explain why he removed it?

If needed I still have his package in my vendor dir so I could put it in a new repo.

**Comment by jphms** [comment]
I just noticed it was removed as well. And since I was really in need of it, here it is https://github.com/jphms/nova-field-sortable. I won't remove it, but I probably won't spend much time maintaining it either. Help yourselves :)

**Comment by lorado** [comment]
Hello together,

I just tried to install this package, and it noticed, that it is currently broken. I was not able to create a model, when sortable field was define in resource.

I found this library here: https://github.com/ofcold/nova-sortable
Seems to be a fork from this package, but not abandoned.

**Comment by adick** [comment]
@lorado for me the create/update form was also broken (javascript error), but I found that it works if you add hideWhenCreating and hideWhenUpdating to the Sortable field: 

`
            Sortable::make(__('Sorting'), 'id')->hideWhenCreating()->hideWhenUpdating(),
`

**Comment by Naxon** [comment]
This is a package I created for my own usage and decided to publish it, therefore I can't promise updates.

I do need to use it again now so I'm fixing some things and will release v2 once it's ready (again, can't promise any timeline).
